### PR TITLE
Get Chip Version and enable Stream Mode

### PR DESCRIPTION
**Pull request by Dr-Dawg**
Get Chip Version and enable Stream Mode - proposed changes to VS1053.cpp and VS1053.h

### CODE REVIEW

**Comment by baldram** [comment]
Thank you for this change @Dr-Dawg . This looks awesome! 🤩 

How about your earlier suggestion mentioned here: 
https://github.com/baldram/ESP_VS1053_Library/discussions/66#discussioncomment-1210542 and here https://github.com/baldram/ESP_VS1053_Library/discussions/66#discussioncomment-1222558 about adjusting examples? 
Or should I do it in a separate change?

Probably within this change we're able to adjust [examples ](https://github.com/baldram/ESP_VS1053_Library/tree/master/examples) to use it:

```c
 if (player.getChipVersion() == 4) { // Only perform an update if we really are using a VS1053, not. eg. VS1003
  player.loadDefaultVs1053Patches(); 
}
```
We can also update example in README.md here: https://github.com/baldram/ESP_VS1053_Library#usage

What do you think?

**Comment by Dr-Dawg** [comment]
Sounds good. I'll do that..

**Comment by Dr-Dawg** [comment]
Done. I updated the Readme (also changed three minutes to three seconds), the examples, and renamed vs1053b-patches.plg to vs1053b-patches.h

**Comment by baldram** [comment]
All right, thanks for changing this `plg` to `h`, so I guess you had an opportunity to test it, that is not causing issues anymore.
In a separate change I will rename also other plg files to h for consistency, and to avoid this already known issue.
Thanks also for catching this little bug in readme about minutes 😄 

Thank you 👍

**Pull request merged**
